config/routes.rb
Rails.application.routes.draw do

  
  resources :rooms
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'pages#all'

  get '/homes' => 'pages#homes'
  get '/experiences' => 'pages#experiences'
  get '/places' => 'pages#places'
  

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
         
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end
  
  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.username = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :image) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :remember_me, :avatar) }
  end
end

def create
  @user = User.create( user_params )
end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def user_params
  params.require(:user).permit(:avatar)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def all
  end

  def homes
  end

  def experiences
  end

  def places
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:home_type, :room_type, :accomodate, :bedroom, :bed, :address, :is_tv, :is_kitchen, :is_internet, :price)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_nav.html.erb
<!-- render separate navbars for user and guest -->

<% if !user_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
  <%= render '/layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">AIRBNB</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Where are you going?">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Become a Host</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Help <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li role="separator" class="divider"></li>
            <li><%= link_to('Create an Account', new_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Log In', new_user_session_path) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
            <ul class="nav row">
              <li class="nav-item">
                <a class="nav-link active col-4 col-sm-3" href="/#all">FOR YOU</a>
              </li>
              <li class="nav-item">
                <a class="nav-link col-4 col-sm-3" href="/homes">HOMES</a>
              </li>
              <li class="nav-item">
                <a class="nav-link col-4 col-sm-3" href="/experiences">EXPERIENCES</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled col-4 col-sm-3" href="/places">PLACES</a>
              </li>
            </ul>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">AIRBNB</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Where are you going?">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Become a Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messages</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li role="separator" class="divider"></li>
            <li><%= link_to('Account Settings', edit_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
            <ul class="nav row">
              <li class="nav-item">
                <a class="nav-link active col-4 col-sm-3" href="/#all">FOR YOU</a>
              </li>
              <li class="nav-item">
                <a class="nav-link col-4 col-sm-3" href="/homes">HOMES</a>
              </li>
              <li class="nav-item">
                <a class="nav-link col-4 col-sm-3" href="/experiences">EXPERIENCES</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled col-4 col-sm-3" href="/places">PLACES</a>
              </li>
            </ul>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbnb clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
</head>
<body>

<%= render '/layouts/nav' %>

<div class="container">
  <span class="notice"><%= notice %></span>
  <span class="alert"><%= alert %></span>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/all.html.erb
<h1>Pages#all</h1>
<p>Find me in app/views/pages/all.html.erb</p>

app/views/pages/experiences.html.erb
<h1>Pages#experiences</h1>
<p>Find me in app/views/pages/experiences.html.erb</p>

app/views/pages/homes.html.erb
<h1>Pages#homes</h1>
<p>Find me in app/views/pages/homes.html.erb</p>

app/views/pages/places.html.erb
<h1>Pages#places</h1>
<p>Find me in app/views/pages/places.html.erb</p>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home_type %><br>
    <%= f.text_field :home_type %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.text_field :room_type %>
  </div>
  <div class="field">
    <%= f.label :accomodate %><br>
    <%= f.text_field :accomodate %>
  </div>
  <div class="field">
    <%= f.label :bedroom %><br>
    <%= f.text_field :bedroom %>
  </div>
  <div class="field">
    <%= f.label :bed %><br>
    <%= f.number_field :bed %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :is_tv %><br>
    <%= f.check_box :is_tv %>
  </div>
  <div class="field">
    <%= f.label :is_kitchen %><br>
    <%= f.check_box :is_kitchen %>
  </div>
  <div class="field">
    <%= f.label :is_internet %><br>
    <%= f.check_box :is_internet %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Home type</th>
      <th>Room type</th>
      <th>Accomodate</th>
      <th>Bedroom</th>
      <th>Bed</th>
      <th>Address</th>
      <th>Is tv</th>
      <th>Is kitchen</th>
      <th>Is internet</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.home_type %></td>
        <td><%= room.room_type %></td>
        <td><%= room.accomodate %></td>
        <td><%= room.bedroom %></td>
        <td><%= room.bed %></td>
        <td><%= room.address %></td>
        <td><%= room.is_tv %></td>
        <td><%= room.is_kitchen %></td>
        <td><%= room.is_internet %></td>
        <td><%= room.price %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home type:</strong>
  <%= @room.home_type %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @room.room_type %>
</p>

<p>
  <strong>Accomodate:</strong>
  <%= @room.accomodate %>
</p>

<p>
  <strong>Bedroom:</strong>
  <%= @room.bedroom %>
</p>

<p>
  <strong>Bed:</strong>
  <%= @room.bed %>
</p>

<p>
  <strong>Address:</strong>
  <%= @room.address %>
</p>

<p>
  <strong>Is tv:</strong>
  <%= @room.is_tv %>
</p>

<p>
  <strong>Is kitchen:</strong>
  <%= @room.is_kitchen %>
</p>

<p>
  <strong>Is internet:</strong>
  <%= @room.is_internet %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>